#!/usr/bin/python3

import re
import sys
import os

ENCODING = 'utf-8'


def escape(path):
    if '/' in path:
        filename_extract = re.compile('(.*/)([a-zA-Z0-9_-]+)(\.xml)$')
        prev = filename_extract.match(path).group(1)
        name = filename_extract.match(path).group(2)
        ext = filename_extract.match(path).group(3)
        output = '{0}{1}_escaped{2}'.format(prev, name, ext)
    else:
        filename_extract = re.compile('([a-zA-Z0-9_-]+)(\.xml)$')
        name = filename_extract.match(path).group(1)
        ext = filename_extract.match(path).group(2)
        output = '{0}_escaped{1}'.format(name, ext)

    with open(path, 'r') as xml_file:
        xml_string = xml_file.read()

    text_pattern = re.compile(
        r'(<[a-zA-Z0-9="?. _-]+>)(\s*([^<]+)\s*)(</[a-zA-Z0-9="?. _-]+>)')

    with open(output, 'w') as file:
        file.write(
            re.sub(text_pattern, '\g<1><![CDATA[\g<2>]]>\g<4>', xml_string))


if __name__ == "__main__":
    xml_pattern = re.compile(r'.*\.xml$')
    if sys.argv[1:] and xml_pattern.match(sys.argv[1]) and os.path.exists(sys.argv[1]):
        escape(sys.argv[1])
    else:
        print('Couldn\'t parse that file')
