#!/usr/bin/python3

import re
import sys
import os
import xml.etree.ElementTree as ET

ENCODING = 'utf-8'


def assess(path):
    feed = ET.parse(path, ET.XMLParser(encoding=ENCODING))
    root = feed.getroot()
    ns = "http://www.bazaarvoice.com/xs/PRR/StandardClientFeed/14.8"
    ET.register_namespace("", ns)

    # for child in root.iter("{%s}EAN" % ns):
    #     print(child.text)


def decode(path):
    with open(path, 'r', encoding=ENCODING) as file:
        strfeed = file.read()

    special_pattern = re.compile(
        r'([^<>=a-zA-Z0-9:/;._!,?@`´#\'\"\n\r\t\s\\\[\]\(\)+*\}\{„“”“‚‘’|^¨€$%~&\u00c0-\u017e™°–-]+)')

    for i in re.findall(special_pattern, strfeed):
        print(i)


if __name__ == "__main__":
    xml_pattern = re.compile(r'.*\.xml$')
    if sys.argv[2:] and xml_pattern.match(sys.argv[1]) and os.path.exists(sys.argv[1]):
        if sys.argv[2] == '--decode':
            decode(sys.argv[1])
        elif sys.argv[2] == '--assess':
            assess(sys.argv[1])
        else:
            print('Provide correct command.')
    else:
        print('Couldn\'t parse that file.')
